version: '3.8'

services:
  mariage-db:
    image: postgres:15
    container_name: mariage-db
    environment:
      POSTGRES_DB: mariage_db
      POSTGRES_USER: mariage_user
      POSTGRES_PASSWORD: vN7ukQ75uUh1xXUrGUoqdqEevPyP2DQo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mariage_user -d mariage_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariage-backend:
    build: .
    container_name: mariage-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://maraige_db_user:vN7ukQ75uUh1xXUrGUoqdqEevPyP2DQo@dpg-d53r0u95pdvs73fodibg-a.oregon-postgres.render.com/maraige_db
      - POSTGRES_HOST=dpg-d53r0u95pdvs73fodibg-a.oregon-postgres.render.com
      - POSTGRES_PORT=5432
      - POSTGRES_DB=maraige_db
      - POSTGRES_USER=maraige_db_user
      - POSTGRES_PASSWORD=vN7ukQ75uUh1xXUrGUoqdqEevPyP2DQo
    depends_on:
      mariage-db:
        condition: service_healthy

  mariage-pgadmin:
    image: dpage/pgadmin4
    container_name: mariage-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mariage.com
      PGADMIN_DEFAULT_PASSWORD: gaellemariage
    ports:
      - "5050:80"
    depends_on:
      - mariage-db

volumes:
  postgres_data: